kind: Pod
apiVersion: v1
metadata:
  name: phpfpm-nginx-example
spec:
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
  containers:
    - name: php
      image: workshop:1
      resources: {}
      ports:
        - containerPort: 9000

    - name: nginx
      image: nginx:1.7.9
      resources: {}
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
