apiVersion: v1
kind: Pod
metadata:
  name: adapter
  labels:
    name: adapter
spec:
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - name: adapter
      image: alpine:3.7
      resources: {}
      volumeMounts:
        - name: shared
          mountPath: /shared
      command:
        - ash
      args:
        - -c
        - while true; do echo ${RANDOM} > /shared/output.txt; sleep 5; done
