apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        application: httpd
    spec:
      containers:
        - name: apache
          image: httpd
          resources:
            limits:
              memory: "20Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
