apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken
spec:
  selector:
    matchLabels:
      app: broken
  template:
    metadata:
      labels:
        app: broken
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "1Mi"
              cpu: "5m"
          ports:
            - containerPort: 80
