apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-me
spec:
  selector:
    matchLabels:
      app: follow-me
  replicas: 2
  template:
    metadata:
      labels:
        app: follow-me
    spec:
      containers:
        - name: follow-me
          image: nginx
